### PR TITLE
Handle ZK connection state and show in the Dashboard

### LINKED ISSUE #49: Improve dashboard ZK connection error message
Gives this error if tries to connect against a non running cluster:
```
error {
 :cause KeeperErrorCode = NoNode for /onyx
 :via
 [{:type org.apache.zookeeper.KeeperException$NoNodeException
   :message KeeperErrorCode = NoNode for /onyx
   :at [org.apache.zookeeper.KeeperException create KeeperException.java 111]}]
```

### LINKED ISSUE #54: Zookeeper connection backoff
We should implement a backoff policy or even just a timeout when trying for a Zookeeper connection.

### PR DESCRIPTION
**Pull request by mariusz-jachimowicz-83**
- [x] Fix #54  
- [x] Fix #49  
- [x] show connection status after dashboard open
- [x] watch connection state
- [x] update connection status in dashboard
- [x] update connection status in console
- [x] close all things properly - properly reloading during dev
- [x] detect connection change very quickly
- [x] try continuously reconnect after connection lost
- [x] understand and solve problem with connection after ZK server restart

``` clojure
; when I restart ZK server
; and I continously call
(defn try-connect [client]
  (println "Trying connect ZK 5s ...")
  (.. client
      (blockUntilConnected 5 TimeUnit/SECONDS)))
; then I see continously
16-09-15 11:28:32 starter-clojure INFO [org.apache.zookeeper.ClientCnxn:975] - Opening socket connection to server 127.0.0.1/127.0.0.1:2188. Will not attempt to authenticate using SASL (unknown error)
16-09-15 11:28:32 starter-clojure INFO [org.apache.zookeeper.ClientCnxn:852] - Socket connection established to 127.0.0.1/127.0.0.1:2188, initiating session
16-09-15 11:28:32 starter-clojure DEBUG [org.apache.zookeeper.ClientCnxn:892] - Session establishment request sent on 127.0.0.1/127.0.0.1:2188
16-09-15 11:28:32 starter-clojure INFO [org.apache.zookeeper.ClientCnxn:1098] - Unable to read additional data from server sessionid 0x1572d95c4ec0006, likely server has closed socket, closing socket connection and attempting reconnect

# I don't understand why ZK is not creating new session
```
- [ ] handle connection lost from log-subscriber 

``` clojure
16-09-16 13:43:01 starter-clojure WARN [onyx.log.zookeeper:291] - Send ConnectionLossException by channel
--- entry
#error {
 :cause KeeperErrorCode = ConnectionLoss for /onyx/da248462-5adc-45b8-a3c8-6fb5516a84c4/log/entry-0000000026
 :via
 [{:type org.apache.zookeeper.KeeperException$ConnectionLossException
   :message KeeperErrorCode = ConnectionLoss for /onyx/da248462-5adc-45b8-a3c8-6fb5516a84c4/log/entry-0000000026
   :at [org.apache.zookeeper.KeeperException create KeeperException.java 99]}]
 :trace
 [[org.apache.zookeeper.KeeperException create KeeperException.java 99]
  [org.apache.zookeeper.KeeperException create KeeperException.java 51]
  [org.apache.zookeeper.ZooKeeper exists ZooKeeper.java 1045]
  [org.apache.curator.framework.imps.ExistsBuilderImpl$3 call ExistsBuilderImpl.java 226]
  [org.apache.curator.framework.imps.ExistsBuilderImpl$3 call ExistsBuilderImpl.java 215]
  [org.apache.curator.RetryLoop callWithRetry RetryLoop.java 107]
  [org.apache.curator.framework.imps.ExistsBuilderImpl pathInForegroundStandard ExistsBuilderImpl.java 211]
  [org.apache.curator.framework.imps.ExistsBuilderImpl pathInForeground ExistsBuilderImpl.java 205]
  [org.apache.curator.framework.imps.ExistsBuilderImpl forPath ExistsBuilderImpl.java 168]
  [org.apache.curator.framework.imps.ExistsBuilderImpl forPath ExistsBuilderImpl.java 39]
  [onyx.log.curator$exists invokeStatic curator.clj 141]
  [onyx.log.curator$exists doInvoke curator.clj 136]
  [clojure.lang.RestFn invoke RestFn.java 425]
  [onyx.log.zookeeper$eval25996$fn__25998$fn__26000 invoke zookeeper.clj 279]
  [clojure.core.async$thread_call$fn__8522 invoke async.clj 434]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}

```
- [x] handle no node exception
- [x] restart deployments watch after reconnected

### CODE REVIEW

**Comment by mariusz-jachimowicz-83** [comment]
Work in progress
Browser notification
notify-browser
Console notification
notify-console

**Comment by lbradstreet** [comment]
The changes so far are great! Thank you for this, it'll improve the usability a lot.

**Comment by MichaelDrogalis** [comment]
Fantastic!!

**Comment by lbradstreet** [comment]
Fantastic work. Works very well for me. 👍

**Pull request merged**
