### PR TITLE
Fix automated test

### PR DESCRIPTION
**Pull request by manuel-uberti**
This is another attempt at fixing the automated test.

I tried to mirror the original code as it was, so I kept commented out calls at `(load-job driver)` and `(check-job-text driver workflow)`.

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Is there anything more I can do to help?

**Comment by lbradstreet** [comment]
Hi Manuel,

Unfortunately it’s a bit hard for me to help figure it out. It doesn’t run on my machine, but I could give you commit access to the repo which would give you access to circleci including SSH. Then you could debug it from there.

Lucas

**Comment by manuel-uberti** [comment]
Hi Lucas,

thank you for the offer. If it's not too much trouble on your side, I'll see what I can do once I have the commit access.

**Comment by lbradstreet** [comment]
Great. I invited you. Hopefully you should be able to see and manually run the build in circleci once you accept.

https://circleci.com/gh/onyx-platform/onyx-dashboard/1581 is for the previous merge.

**Comment by manuel-uberti** [comment]
Thanks. I'll look into it as soon as possible.

**Comment by manuel-uberti** [comment]
Sorry, I haven't had time to look into it. Also, we are not using Onyx at the moment so I am not sure when I'll be able to look into this again.

**Comment by lbradstreet** [comment]
No worries. Thanks for trying anyway!

**Pull request closed without merging**
